/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-01 01:28:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/main.jsp", Long.valueOf(1727656830034L));
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1727683397409L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1727149322783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
 String contextPath=request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Insert title here</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/header.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("            <div id=\"headerSticky\">\r\n");
      out.write("                <div id=\"headerLeft\">\r\n");
      out.write("                    <div id=\"logo\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Logo.png\" alt=\"Logo\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"headerCenter\">\r\n");
      out.write("                    <div id=\"centerMenu\">\r\n");
      out.write("                        <ul class=\"nav\">\r\n");
      out.write("                            <li><a href=\"#\">New</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">\r\n");
      out.write("                                        <!-- Bootstrap Carousel -->\r\n");
      out.write("                                        <div id=\"newProductSlide\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                                            <!-- Carousel indicators (선택 사항) -->\r\n");
      out.write("                                            <ol class=\"carousel-indicators\">\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"0\" class=\"active\">\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"1\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"2\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"3\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"4\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"5\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"6\"></li>\r\n");
      out.write("                                                <li data-target=\"#newProductSlide\" data-slide-to=\"7\"></li>\r\n");
      out.write("                                            </ol>\r\n");
      out.write("\r\n");
      out.write("                                            <!-- Carousel slides -->\r\n");
      out.write("                                            <div class=\"carousel-inner\">\r\n");
      out.write("                                                <div class=\"carousel-item active\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Kalimero.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Kalimero</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/lewis.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Lewis</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Ellipse.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Ellipse</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Diago.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Diago</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Andiamo.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Andiamo</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Liberta.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Liberta</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/SignatureKnot.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>SignatureKnot</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Orbit.jpg\"\r\n");
      out.write("                                                        class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                        <p>Orbit</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                        <div class=\"sub-menu\">Submenu 3</div>\r\n");
      out.write("                                        <div class=\"sub-menu\">Submenu 4</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Women</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 1\r\n");
      out.write("                                        <div class=\"sub-menu\">\r\n");
      out.write("                                            <!-- Bootstrap Carousel -->\r\n");
      out.write("                                            <div id=\"newProductSlide\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                                                <!-- Carousel indicators (선택 사항) -->\r\n");
      out.write("                                                <ol class=\"carousel-indicators\">\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"0\" class=\"active\">\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"1\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"2\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"3\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"4\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"5\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"6\"></li>\r\n");
      out.write("                                                    <li data-target=\"#newProductSlide\" data-slide-to=\"7\"></li>\r\n");
      out.write("                                                </ol>\r\n");
      out.write("    \r\n");
      out.write("                                                <!-- Carousel slides -->\r\n");
      out.write("                                                <div class=\"carousel-inner\">\r\n");
      out.write("                                                    <div class=\"carousel-item active\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Kalimero.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Kalimero</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/lewis.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Lewis</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Ellipse.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Ellipse</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Diago.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Diago</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Andiamo.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Andiamo</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Liberta.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Liberta</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/SignatureKnot.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>SignatureKnot</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"carousel-item\">\r\n");
      out.write("                                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/Orbit.jpg\"\r\n");
      out.write("                                                            class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                                            <p>Orbit</p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 3</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 4</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 5</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 6</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 7</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 8</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Men</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 1</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 3</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 4</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 5</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 6</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 7</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 8</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Home</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 1</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Gift</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 1</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 3</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 4</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Inside Bottega</a>\r\n");
      out.write("                                <div class=\"dropdown-content\">\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 1</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 2</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 3</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 4</div>\r\n");
      out.write("                                    <div class=\"sub-menu\">Submenu 5</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"headerRight\">\r\n");
      out.write("                    <div id=\"rightMenu\">\r\n");
      out.write("                        <div id=\"searchBtn\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                fill=\"none\" stroke=\"black\" stroke-width=\"2\" stroke-linecap=\"round\"\r\n");
      out.write("                                stroke-linejoin=\"round\">\r\n");
      out.write("                                <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\r\n");
      out.write("                                <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"phoneBtn\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                fill=\"none\" stroke=\"black\" stroke-width=\"2\" stroke-linecap=\"round\"\r\n");
      out.write("                                stroke-linejoin=\"round\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                    d=\"M22 16.92V19a2 2 0 0 1-2.18 2 19.88 19.88 0 0 1-8.63-3.16 19.51 19.51 0 0 1-6-6A19.88 19.88 0 0 1 3 4.18 2 2 0 0 1 5 2h2.09a2 2 0 0 1 2 1.72 12.05 12.05 0 0 0 .56 2.57 2 2 0 0 1-.45 2L7.91 9.91a16 16 0 0 0 6 6l1.62-1.62a2 2 0 0 1 2-.45 12.05 12.05 0 0 0 2.57.56 2 2 0 0 1 1.72 2.03z\">\r\n");
      out.write("                                </path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                fill=\"none\" stroke=\"black\" stroke-width=\"2\" stroke-linecap=\"round\"\r\n");
      out.write("                                stroke-linejoin=\"round\">\r\n");
      out.write("                                <!-- Circle for the head -->\r\n");
      out.write("                                <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                                <!-- Rectangle for the body (width = 16) -->\r\n");
      out.write("                                <rect x=\"4\" y=\"12\" width=\"16\" height=\"10\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                fill=\"none\" stroke=\"black\" stroke-width=\"2\" stroke-linecap=\"round\"\r\n");
      out.write("                                stroke-linejoin=\"round\">\r\n");
      out.write("                                <!-- Bag shape -->\r\n");
      out.write("                                <rect x=\"4\" y=\"7\" width=\"16\" height=\"14\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                <!-- Bag handles -->\r\n");
      out.write("                                <path d=\"M8 7a4 4 0 0 1 8 0\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"mainContainer\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"videoContainer\">\r\n");
      out.write("            <div id=\"player\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("        <div id=\"footerMain\">\r\n");
      out.write("            <div id=\"footerMenu\">\r\n");
      out.write("                <div id=\"menuColumn1\">\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Newsletter</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Sustainability</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Store location</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Kakaotalk Channel</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Youtube</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"menuColumn2\">\r\n");
      out.write("                     <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Customer Care</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">FAQ</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">My order</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Our services</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"menuColumn3\">\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Careers</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Terms</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Privacy policy</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Cookies</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"menuColumn4\">\r\n");
      out.write("                    <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Shipping to : Republic of Korea</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"columnSection\">\r\n");
      out.write("                        <a href=\"\">Language: English</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footerInfo\">\r\n");
      out.write("            Bottega Veneta Korea LLC | Business Registration No. 211-87-11506 <br>\r\n");
      out.write("            Address of the company: 12F, 458, Dosan-daero, Gangnam-gu, Seoul, Republic of Korea | <a href=\"\">Legal Notice</a><br>\r\n");
      out.write("            Name of representative as recorded in the Business registration certificate: Hajung Kim <br>\r\n");
      out.write("            Telecommunication registration number: 2022-Seoul-Gangnam-06160 <br>\r\n");
      out.write("            Organization who issued telecommunication registration number: Seoul Gangnam gu office <br>\r\n");
      out.write("            Hosting service: Salesforce Commerce Cloud <br>\r\n");
      out.write("            <a href=\"\">Certificate of insurance subscription</a><br>\r\n");
      out.write("            Customer Center: <a href=\"\">+ 82 70 4784 4026</a>| E-mail: <a href=\"\">customercare.kr@bottegaveneta.com</a>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"copyRight\">Â© 2024 Bottega Veneta</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // IFrame API를 비동기로 로드\r\n");
      out.write("        var tag = document.createElement('script');\r\n");
      out.write("        tag.src = \"https://www.youtube.com/iframe_api\";\r\n");
      out.write("        var firstScriptTag = document.getElementsByTagName('script')[0];\r\n");
      out.write("        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);\r\n");
      out.write("\r\n");
      out.write("        // YouTube API 로드 후 호출되는 콜백 함수\r\n");
      out.write("        function onYouTubeIframeAPIReady() {\r\n");
      out.write("            new YT.Player('player', {\r\n");
      out.write("                height: '100%', // 부모 요소의 높이 사용\r\n");
      out.write("                width: '100%', // 부모 요소의 너비 사용\r\n");
      out.write("                videoId: 'T2CwGpJGWxg', // YouTube 비디오 ID\r\n");
      out.write("                playerVars: {\r\n");
      out.write("                    'autoplay': true, // 자동 재생\r\n");
      out.write("                    'mute': 1, // 음소거\r\n");
      out.write("                    'controls': 0, // 플레이어 컨트롤 숨기기\r\n");
      out.write("                    'loop': true, // 반복 재생\r\n");
      out.write("                    'playlist': 'T2CwGpJGWxg', // 같은 동영상 ID를 playlist에 추가\r\n");
      out.write("                    'showinfo': 0, // 비디오 제목 및 uploader 정보 숨기기\r\n");
      out.write("                    'modestbranding': 1, // YouTube 로고 최소화\r\n");
      out.write("                    'rel': 0, // 관련 비디오 숨기기\r\n");
      out.write("                    'iv_load_policy': 3 // 주석(인포그래픽) 숨기기\r\n");
      out.write("                },\r\n");
      out.write("                events: {\r\n");
      out.write("                    'onReady': onPlayerReady,\r\n");
      out.write("                    'onStateChange': onPlayerStateChange\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 플레이어가 준비되었을 때 호출되는 함수\r\n");
      out.write("        function onPlayerReady(event) {\r\n");
      out.write("            event.target.playVideo(); // 비디오 자동 재생\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 플레이어 상태 변경 시 호출되는 함수\r\n");
      out.write("        function onPlayerStateChange(event) {\r\n");
      out.write("            if (event.data === YT.PlayerState.ENDED) {\r\n");
      out.write("                event.target.playVideo(); // 비디오가 끝났을 때 다시 재생\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 스페이스바 키 입력 무시\r\n");
      out.write("        document.addEventListener('keydown', function(event) {\r\n");
      out.write("            if (event.code === 'Space') {\r\n");
      out.write("                event.preventDefault(); // 기본 동작 차단\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
